# Generated by Django 3.2.21 on 2024-01-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compliant',
            fields=[
                ('compliant_id', models.AutoField(primary_key=True, serialize=False)),
                ('complaint', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('student_id', models.IntegerField()),
                ('reply', models.CharField(max_length=42)),
            ],
            options={
                'db_table': 'compliant',
                'managed': False,
            },
        ),
    ]
