# Generated by Django 3.2.21 on 2024-01-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=60)),
                ('mobile_number', models.IntegerField(db_column='mobile number')),
            ],
            options={
                'db_table': 'teacher',
                'managed': False,
            },
        ),
    ]
