# Generated by Django 3.2.21 on 2024-01-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('form_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=300)),
                ('age', models.IntegerField()),
                ('dob', models.DateField(db_column='DOB')),
                ('mobile_number', models.IntegerField(db_column='mobile number')),
                ('gender', models.CharField(max_length=15)),
                ('parents_name', models.CharField(db_column='parents name', max_length=60)),
                ('guardian_relationship', models.CharField(db_column='guardian relationship', max_length=20)),
                ('courses_opted', models.CharField(db_column='courses opted', max_length=500)),
                ('parents_number', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'form',
                'managed': False,
            },
        ),
    ]
