# Generated by Django 3.2.21 on 2024-01-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('cvv', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('card_number', models.IntegerField(db_column='card number')),
                ('upi', models.CharField(max_length=50)),
                ('net_banking', models.IntegerField(db_column='net banking')),
                ('card_holder_name', models.CharField(db_column='card holder name', max_length=50)),
            ],
            options={
                'db_table': 'payment',
                'managed': False,
            },
        ),
    ]
