# Generated by Django 3.2.21 on 2024-01-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allotment',
            fields=[
                ('allotment_id', models.AutoField(primary_key=True, serialize=False)),
                ('cap_id', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('dob', models.DateField(db_column='DOB')),
                ('address', models.CharField(max_length=300)),
                ('mobile_number', models.CharField(db_column='mobile number', max_length=11)),
            ],
            options={
                'db_table': 'allotment',
                'managed': False,
            },
        ),
    ]
