# Generated by Django 3.2.21 on 2024-01-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('register_id', models.IntegerField(unique=True)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('course_id', models.IntegerField()),
            ],
            options={
                'db_table': 'student',
                'managed': False,
            },
        ),
    ]
